execute at @e[type=fb:stage_plate_freddy] positioned ~~~ run tp @e[type=fb:showtime_freddy_fazbear,r=10] ~ ~-0.5 ~
execute at @e[type=fb:stage_plate_bonnie_bunny] positioned ~~~ run tp @e[type=fb:showtime_bonnie_bunny,r=10] ~ ~-0.5 ~
execute at @e[type=fb:stage_plate_chica_chicken] positioned ~~~ run tp @e[type=fb:showtime_chica_chicken,r=10] ~ ~-0.5 ~
execute at @e[type=fb:stage_plate_foxy] positioned ~~~ run tp @e[type=fb:showtime_foxy,r=10] ~ ~-0.5 ~
execute at @e[type=fb:stage_plate_possed_springbonnie] positioned ~~~ run tp @e[type=fb:showtime_possed_springbonnie,r=10] ~ ~-0.5 ~
execute at @e[type=fb:stage_plate_possed_fredbear] positioned ~~~ run tp @e[type=fb:showtime_possed_fredbear,r=10] ~ ~-0.5 ~
execute at @e[type=fb:stage_plate_toy_bonnie_nm] positioned ~~~ run tp @e[type=fb:showtime_toy_bonnie_nm,r=10] ~ ~-0.5 ~
execute at @e[type=fb:stage_plate_toy_freddy_nm] positioned ~~~ run tp @e[type=fb:showtime_toy_freddy_nm,r=10] ~ ~-0.5 ~
execute at @e[type=fb:stage_plate_toy_chica_nm] positioned ~~~ run tp @e[type=fb:showtime_toy_chica_nm,r=10] ~ ~-0.5 ~
execute at @e[type=fb:stage_plate_toy_foxy_nm] positioned ~~~ run tp @e[type=fb:showtime_toy_foxy_nm,r=10] ~ ~-0.5 ~
execute at @e[type=fb:stage_plate_withered_bonnie_nm] positioned ~~~ run tp @e[type=fb:showtime_withered_bonnie_nm,r=10] ~ ~-0.5 ~
execute at @e[type=fb:stage_plate_withered_freddy_nm] positioned ~~~ run tp @e[type=fb:showtime_withered_freddy_nm,r=10] ~ ~-0.5 ~
execute at @e[type=fb:stage_plate_withered_chica_nm] positioned ~~~ run tp @e[type=fb:showtime_withered_chica_nm,r=10] ~ ~-0.5 ~
execute at @e[type=fb:stage_plate_withered_foxy_nm] positioned ~~~ run tp @e[type=fb:showtime_withered_foxy_nm,r=10] ~ ~-0.5 ~